# port
# contextPath
# thymeleaf
server:
  port: 8080
  servlet:
    context-path: /
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/haitong_oa?serverTimezone=GMT
    username: root
    password: etoak
  servlet:
    multipart:
      max-file-size: 20MB
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.haitong.bean
pagehelper:
  reasonable: true
  helper-dialect: mysql
logging:
  level:
    com.etoak.mapper: debug

upload:
  path: /files/**
  location: file:f:/image/
